{{- with index .Values "cluster-configs" "secrets" "db" }}
{{- if index . "password" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  username: {{ index $.Values "cluster-configs" "secrets" "db" "username" | b64enc | quote }}
  password: {{ index $.Values "cluster-configs" "secrets" "db" "password" | b64enc | quote }}
  flyway-username: {{ index $.Values "cluster-configs" "secrets" "db" "flywayUsername" | b64enc | quote }}
  flyway-password: {{ index $.Values "cluster-configs" "secrets" "db" "flywayPassword" | b64enc | quote }}
---
{{- end }}
{{- end }}

